### ISSUE TITLE
The id of the captcha should be returned

### ISSUE THREAD

**Issue by 3ynm** [2captcha/2captcha-ruby#7]
You should be able to pass the return_id option to all captcha solving methods, otherwise there's no way to report a good or bad captcha answer.

I've been told that it's recommended to report all captchas as good or bad, so maybe instead of 1 method that does it all, the default behavior should involve 3 steps: first send the request and return the id, then get the token, and then report its effectiveness.

You could also return the id and token on a single method.

**Comment by PBadicean** [comment]
Hello, do you need each method to return an captcha_id so that you can later send it to the report? Thanks, we will add this to the current functionality

**Comment by 3ynm** [comment]
I'm no longer using 2captcha, but yes, adding the feature to return the captcha id would be useful.

**Comment by PBadicean** [comment]
We are very sorry that our service turned out to be of little use to you, however, if you describe in detail the problem that you had using our service, our technical specialists will try to help you. We sincerely hope that we will be able to help you and continue further cooperation.
