### ISSUE TITLE
Api2Captcha::Client methods do not work with Ruby 3.1

### ISSUE THREAD

**Issue by JasonBarnabe** [2captcha/2captcha-ruby#9]
e.g. `#turnstile` calls `#solve` like so:

```ruby
solve("turnstile", params)
```

but `#solve`'s signature is

```ruby
def solve(method, file_path = nil, return_id: false, **params)
```

So `file_path` gets the params, and `params` is an empty Hash. Looks like this was caused by #8.

**Comment by kratzky** [comment]
Should be fixed in v1.1.1
